name: Bug report
description: Report a bug or incompatible CSV/TSV export format
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what actually happened?
      placeholder: "Steps + expected vs actual"
    validations:
      required: true

  - type: textarea
    id: csv_header
    attributes:
      label: CSV/TSV header row
      description: Paste the header row here (remove sensitive data if needed).
      render: text
    validations:
      required: true

  - type: textarea
    id: samples
    attributes:
      label: Sample rows (optional)
      description: Paste 1-2 sample rows (please remove sensitive content).
      render: text
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / error message (optional)
      description: If available, paste the in-app error text or the Vault log file section.
      render: text
    validations:
      required: false

